### PR TITLE
added discount code field to Payment method/Shipping step

### PR DESCRIPTION
**Pull request by alex-vo**
Fixed [#906].

### CODE REVIEW

**Review by alfredsgenkins — CHANGES_REQUESTED** [review]
No question to code, but!

When playing with functionality, it seems to `Order Total` does not update properly, if the discount is applied after `Shipping Step` was completed.

**Comment by alfredsgenkins** [comment]
Please make sure this functionality is only available on Shipping step.

**Comment by lion152** [comment]
This functionality should be available in both Shipping and Checkout steps, as it is in default Magento.

**Comment by alfredsgenkins** [comment]
image

This does not look fixed. Is this some BE / FE synchronization? Why does reload solves the issue? Maybe we need to re-call the total?

**Comment by alex-vo** [comment]
Rechecked the flow again. Works as expected.

**Pull request merged**
