### PR TITLE
Stripe integration

### PR DESCRIPTION
**Pull request by rMazeiks**
As asked, I am creating a work-in-progress PR. Currently, the integration is functioning, but the API key is hard-coded.

Depends on https://github.com/scandipwa/quote-graphql/pull/17

Remaining tasks (see todo comments):
- Replace hard-coded api key with the one from the Stripe config (not currently served through GraphQL yet)
- Refactor handleAuthorization a bit

Anželika Lujāne and Edgars Liseks did most of the work on this feature, I will merely improve it and fix bugs if any.

### CODE REVIEW

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/CheckoutBilling/CheckoutBilling.container.js  1
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.component.js  4
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.container.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4570096&bid=15362004)

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.container.js  1
- src/app/component/CheckoutBilling/CheckoutBilling.container.js  1
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.component.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4570096&bid=15362004)

**Comment by rMazeiks** [comment]
I have now replaced the hard-coded API keys, improved some of the code quality, and debugged issues with 3D secure payments - task is ready for CR! :tada: :smile: :checkered_flag: 

Since Stripe does not serve the publishable API keys in GraphQl, this functionality was implemented in a new module. This feature requires the new stripe-graphql module to be added:

https://github.com/rMazeiks/stripe-graphql

There is also an update to the quote-graphql module - see PR https://github.com/scandipwa/quote-graphql/pull/17

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/CheckoutBilling/CheckoutBilling.container.js  2
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.component.js  3
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.container.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4570096&bid=15362004)

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.container.js  1
- src/app/component/Stripe/Stripe.component.js  3
- src/app/component/Stripe/Stripe.container.js  2
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.component.js  3
- src/app/component/CheckoutBilling/CheckoutBilling.container.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4570096&bid=15362004)

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.container.js  1
- src/app/component/CheckoutBilling/CheckoutBilling.container.js  2
- src/app/component/InjectedStripeCheckoutForm/InjectedStripeCheckoutForm.component.js  3
- src/app/component/Stripe/Stripe.container.js  2
- src/app/component/Stripe/Stripe.component.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4570096&bid=15362004)

**Pull request merged**
