### PR TITLE
Inventory allowed min / max qty check

### PR DESCRIPTION
**Pull request by atravkovs**
Depends on:
 - https://github.com/scandipwa/catalog-graphql/pull/30
 - https://github.com/scandipwa/quote-graphql/pull/16

### CODE REVIEW

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/ProductActions/ProductActions.container.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4493423&bid=15153150)

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/ProductActions/ProductActions.container.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4493423&bid=15153150)

**Comment by alfredsgenkins** [comment]
@all-contributors please add @atravkovs for code, ideas, review, question

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/ProductActions/ProductActions.container.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4493423&bid=15153150)

**Pull request merged**
