### PR TITLE
Product compare

### PR DESCRIPTION
**Pull request by edgars1337**
image
image
attributes only get compared if they are set to comparable in adminpanel
changes were made to this module https://github.com/scandipwa/compare-graphql/pull/2 to fully support comparing products. it still needs to be added as a dependency to the theme, but since the changes are not on the default branch i'm not sure how would that work.
the enabling/disabling of the compare thing (like listed in the ticket), is only stopping visual contents relating to the compare page from rendering, route will still exist tho. maybe there's a better solution for that.

### CODE REVIEW

**Comment by alfredsgenkins** [comment]
PDP

What happens with that button if user loggs in? Will it go to next line?

Compare

Please make sure title is always in one line, if longer add ...

**Comment by edgars1337** [comment]
image
currently on PDP ir pushes down the "go to wishlist button"
will address the Compare one line title right now

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/ProductCompareCard/ProductCompareCard.component.js  3
- src/app/util/AttributeValue/AttributeValue.js  5
- src/app/component/ProductCompareButton/ProductCompareButton.container.js  4
- src/app/query/CompareProduct.query.js  1
- src/app/store/Compare/Compare.action.js  1
- src/app/route/Compare/Compare.container.js  1
- src/app/route/Compare/Compare.component.js  7
- src/app/component/Header/Header.component.js  1
- src/app/store/Compare/Compare.reducer.js  6
- src/app/query/ProductCompare.query.js  2
- src/app/store/Compare/Compare.dispatcher.js  3
- src/app/component/ProductCompareButton/ProductCompareButton.component.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4533233&bid=15257524)

**Comment by Danpiel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/component/Header/Header.component.js  1
- src/app/component/ProductCompareButton/ProductCompareButton.container.js  4
- src/app/store/Compare/Compare.action.js  1
- src/app/store/Compare/Compare.reducer.js  6
- src/app/query/CompareProduct.query.js  1
- src/app/route/Compare/Compare.container.js  1
- src/app/route/Compare/Compare.component.js  7
- src/app/util/AttributeValue/AttributeValue.js  5
- src/app/component/ProductCompareButton/ProductCompareButton.component.js  3
- src/app/component/ProductCompareCard/ProductCompareCard.component.js  3
- src/app/query/ProductCompare.query.js  2
- src/app/store/Compare/Compare.dispatcher.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/base-theme/base-theme/pullRequest?prid=4533233&bid=15257524)

**Comment by alfredsgenkins** [comment]
@all-contributors add @edgars1337  for code

**Comment by yeegor** [comment]
I think it's time to revisit this!
@alfredsgenkins please do.

**Comment by alfredsgenkins** [comment]
Closing this issue. We will re-implement this. Thanks for the contribution tho! :heart:

**Pull request closed without merging**
