### PR TITLE
[SWPWA-290] GTM - Google Tag Manager

### PR DESCRIPTION
**Pull request by dmitrijs-voronovs**
Integrated GTM into SWPWA according to this spreadsheet https://docs.google.com/spreadsheets/d/16Z86QjTXTQ5dLUH6yoi33y2ke-VQtFvmEgqoBw1iZl8/edit?usp=sharing

Depends on:
*  https://github.com/dmitrijs-voronovs/GTM
* https://github.com/dmitrijs-voronovs/GTM-graphql 

 How to test:
1. Register at [tagmanager.google.com](tagmanager.google.com) by mentioning the link of target website.
2. Get GTM_ID, that looks like `GTM-XXXXXXX`
3. In Magento Admin go to `Stores > Configuration > Scandiweb > PWA Google Tag Manager`
4. Insert GTM_ID and enable GTM as follows
image
5. On GTM website next to the GTM_ID click on preview button 
image
6. Refresh the target website.
7. Track all events
Selection_185

### CODE REVIEW

**Comment by megazoor** [comment]
Hello! Thank you for this contribution!

Would you mind sharing how you were able to get the base_theme to install into the scandipwa/docker implementation? 

I have tried the following:
1. dump base theme into: src/localmodules/base_theme
2. (this is where i am unsure) --> i need something like this, although i know this command doesnt exist..??? composer repository add path ./src/localmodules/base-theme
3. composer update scandipwa/source

Thank you in advance

**Comment by dmitrijs-voronovs** [comment]
> Hello! Thank you for this contribution!
> 
> Would you mind sharing how you were able to get the base_theme to install into the scandipwa/docker implementation?
> 
> I have tried the following:
> 
> 1. dump base theme into: src/localmodules/base_theme
> 2. (this is where i am unsure) --> i need something like this, although i know this command doesnt exist..??? composer repository add path ./src/localmodules/base-theme
> 3. composer update scandipwa/source
> 
> Thank you in advance

@megazoor Please, try following the `Quick start` guide described here https://github.com/scandipwa/scandipwa-base

**Comment by dmitrijs-voronovs** [comment]
Possible issues:

- On some pages, nothing is pushed to the dataLayer, probably, due to the fact that we are waiting for some data. The issue is often seen with impressions & details
- 'https://tagmanager.google.com/debug' is not whitelisted
- “List” - does not equal to the page title
- “Price” - sale price is not tracked
- "category" - category variable is missing from the
- “portalName’/’categoryName”/”categoryGroupName” - wrong data, do not equal to the breadcrumbs, remove those
- “Currency” - found in the product object, remove from there
- Remove from a cart on “remove” button click in the dropdown - incorrect quantity of products removed
- Number of checkout steps is more than there actually is - remove 3d step
- "coupon" variable in purchase - push empty string if coupon is not applied
- Check product utility if all data passed correctly

**Comment by alfredsgenkins** [comment]
Closing for now. Must be moved into extension.

**Pull request closed without merging**
