### PR TITLE
Added product and category canonical URL to head

### PR DESCRIPTION
**Pull request by kandrejevs**

### CODE REVIEW

**Comment by alfredsgenkins** [comment]
Please add canonical to category, then we can merge this :)

**Comment by alfredsgenkins** [comment]
Also, after completed category, fix CODACY issues.

**Comment by kandrejevs** [comment]
@alfredsgenkins This will require changes in scandipwa/catalog-graphql module I will add soon

**Comment by kandrejevs** [comment]
https://github.com/scandipwa/catalog-graphql/pull/9

here is pull request that adds canonical_url to category attributes

**Comment by alfredsgenkins** [comment]
@kandrejevs Changes merged to `scandipwa/catalog-graphql`, can proceed with category.

**Comment by kandrejevs** [comment]
It's already here

**Pull request merged**
